"""remove verification token

Revision ID: 6922bfc128e1
Revises: 4be27e588912
Create Date: 2026-09-25 19:06:24.071069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6922bfc128e1'
down_revision: Union[str, Sequence[str], None] = '4be27e588912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_verification_token'), 'users', type_='unique')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_users_verification_token'), 'users', ['verification_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
